name: Update combined reservations calendar

on:
  workflow_dispatch: {}
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm install node-ical ical-generator

      - name: Build calendar.ics
        env:
          AIRBNB_ICS_URL: ${{ secrets.AIRBNB_ICS_URL }}
          BOOKING_ICS_URL: ${{ secrets.BOOKING_ICS_URL }}
        run: |
          node build.mjs

      - name: Commit updated calendar
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add calendar.ics
          git commit -m "Update calendar.ics" || echo "No changes"
          git push
